project:
  type: book
  output-dir: docs

book:
  title: "MTH 401 :: Real Analysis <br>Fall 2024"
  #subtitle: "Fall 2024"
  navbar:
    background: "#D0B8A8"
    right:
      - href: about.qmd
        text: aboot
  sidebar:
    background: "#F8EDE3"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2


  chapters:
    - index.qmd
    - glance.qmd
    - syllabus.qmd
    - inquiry.qmd
    - support.qmd
    - structure.qmd
    - writing.qmd
    - grades.qmd
    - UPElements.qmd

format:
  html:
    #theme: litera
    theme: simplex
    css: style/mth401.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual
