---
title: "Inquiry Based Learning"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---


We will use a method of instruction often called Inquiry Based Learning (IBL) which is designed to engage and foster skills and habits that working mathematicians use regularly; you will be asked to solve problems, make conjectures, experiment, explore, create, collaborate, and communicate your work with your peers. Rather than giving you facts to memorize or showing you clear paths to solutions, my role is to guide you via a sequence of carefully chosen problems through a journey of mathematical discovery.

Throughout the semester, you will receive lists of definitions to interpret and make sense of, as well as exercises and theorems which you and your classmates will answer or prove. There will be very little traditional lecture. Instead, class time will consist of student presentations of new material. For best results, you should come to class prepared to share your work or ideas about that day's problems. This method of inquiry does not work nearly as well if you're looking at a problem for the first time in-class.

You will be asked to share your solutions in class regularly. You will also be encouraged to critique the problems (reformulating them if needed), to generate examples and counterexamples to theorems or conjectures, to conjecture new theorems based on what you've learned, and to prove or disprove these conjectures. When observing another student's presentation, it is your responsibility to follow their argument closely and decide if they have seems reasonable. If you cannot follow their logic, or have questions about their solution, it is your responsibility to ask!

::: {.callout-warning appearance=simple}
A key feature of the IBL method is student **discovery** and therefore **outside resources are not allowed.** This means that you should not consult texts (other than the one handed out in class), the internet, students not currently enrolled in the course, or faculty other than myself. Consulting outside resources will only deprive yourself of opportunities to engage with the material. You are encouraged to work with your classmates on the problems, although for best results you should get as far as you can on your own before collaborating. It's important that you do not feel overwhelmed -- so please let me know if you're stuck on a problem and I'll be happy to give you hints.
:::
