---
title: "Course Structure"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## Daily Work

Your standing assignment in this course is to work out and prepare solutions / proofs for the exercises in the class notes. Keep track of what problems we cover in class so that you can work ahead and come to class prepared to discuss your work and share your ideas, both in small groups and as a whole class. If you get stuck on a problem, come prepared to ask questions.

::: {.callout-note appearance=simple}
I will post on Moodle a running account of what material we cover each day so that if you happen to miss class, you can still keep track of where we are in the notes.
:::


## Written Homework

Roughly once per week, I will ask you to hand in write-ups of selected problems. The goal of these written assignments is to practice your understanding of the material as well as your communication of mathematics. I will provide feedback on your work after which you are welcome to revise and resubmit for further feedback if you wish. You may choose to use some of these problems as evidence of your progress in the course.  Guidelines for written work can be found in 
[Section @sec-writing].

You are welcome to write your homework assignments by hand, but you might also choose use this opportunity to learn to use $\LaTeX$ (pronounced LAY-TEK). This is the typesetting system your professors use to write documents that have math notation. There are several free ways to use \LaTeX, the easiest of which is probably the web-based [Overleaf](http://overleaf.com).  Since it's web-based, there's nothing to install.  Look for the free student version.

## Synthesis Problems

Throughout the semester, we will encounter problems whose solutions require the synthesis of multiple concepts and results from the course.  These will be more varied and more challenging and will typically require deep thought over an extended period of time.   You will likely find that you will hit some dead ends along the way. As with all
mathematical research, the key is to learn from what doesn’t work and to persist through the difficulties. The aha moment
that will eventually come will be worth the wait!


## Due Dates

Here is how due dates work in the non-academic world: they exist and they're usually there for a reason, but they're usually somewhat flexible.  In this class, they are meant to help you organize your time and to help me from getting overwhelmed with work. But if you need a little more time (no more than a few days) to work on something, that is usually fine. Just send me an email to let me know that your work will be late. You do not need to provide a reason.  If you need more than a few days, you should come talk with me about it.  

## Proof Portfolio

As we proceed through the course material, I will ask you to select examples of your work that exemplifying your understanding and engagement with the class content.  At the end of the semester, this portfolio will provide evidence of your learning throughout the semester.  To give me time to review your portfolio, please plan on submitting your portfolio to me by the last day of classes, Dec. 5th.  There is no prescribed format for your portfolio -- many students create a Google Doc that they can then share with me, but if you have other ideas, just let me know!

## Class Proof Journal

Over the course of the semester, we will collaboratively create a proof journal consisting of solutions for each problem that have been presented in class. You can think of this as a textbook for the class, and you may refer to these solutions (with proper attribution) in your own work.

## Exams

We will have a mid-semester take home exam the week of Oct. 8th which will give you a chance to reflect on the material that we've covered up to that point. Instead of a traditional final exam, there will have a final reflection assignment to be completed anytime before the end of finals week which will give you an opportunity to reflect on and synthesize some of the main themes of the course. You will also be asked to self-assess your learning over the course of the semester.
